/**
 *  Difficulty: Easy
 *
 * # 389. Find the Difference
 *
 * You are given two strings s and t.
 *
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 *
 * Return the letter that was added to t.
 *
 * **Example:**
 *
 * <dl class="example-details">
 * <dt>Input:</dt>
 * <dd>"abcd", t = "abcde"</dd>
 * <dt>Output:</dt>
 * <dd>'e' (the added character)</dd>
 * <dt>Explanation:</dt>
 * <dd>Character 'e' was added to 'abcd' to make 'abcde'</dd>
 * </dl>
 *
 * <details>
 * <summary><b>🔍 SOLUTION EXPLANATION</b></summary>

 * ### METADATA:
 * **Techniques**: Bitwise Operations, Bit Masking
 * **Data Structures**: Integer (as bit array)
 * **Patterns**: Bit Manipulation Pattern, XOR Properties
 * **Time Complexity**: **O(n)
 * **Space Complexity**: **O(1)

 *
 * ### INTUITION:
 * This problem uses bitwise operations to manipulate individual bits, providing elegant solutions with optimal space complexity.
 *
 * ### APPROACH:
 * 1. **Analyze the problem**: Understand the input constraints and expected output
 * 2. **Choose the right technique**: Apply bit manipulation methodology
 * 3. **Implement efficiently**: Focus on optimal time and space complexity
 * 4. **Handle edge cases**: Consider boundary conditions and special cases
 *
 * ### WHY THIS WORKS:
 * - The solution leverages bit manipulation principles
 * - Time complexity is optimized for the given constraints
 * - Space complexity is minimized where possible
 *
 * ### EXAMPLE WALKTHROUGH:
 * ```
 * Input: s = "abcd", t = "abcde"
 * Step 1: XOR all characters
 *   result = 0
 *   XOR s: result ^= ord('a') ^= ord('b') ^= ord('c') ^= ord('d')
 *   XOR t: result ^= ord('a') ^= ord('b') ^= ord('c') ^= ord('d') ^= ord('e')
 *
 * Step 2: Duplicate characters cancel out
 *   All characters in s cancel with t
 *   Remaining: ord('e')
 *
 * Step 3: Convert back to character
 *   result = ord('e') → 'e'
 *
 * Output: 'e' (the added character)
 * ```
 *
 * ### TIME COMPLEXITY:
 * O(n)
 *
 * ### SPACE COMPLEXITY:
 * O(1)
 *
 * ### EDGE CASES:
 * - Empty input handling
 * - Single element cases
 * - Large input considerations
 *
 * </details>
 */

/**
 * Main solution for Problem 389: Find the Difference
 *
 * @param {string} s - Original string
 * @param {string} t - Shuffled string with one extra character
 * @return {string} - The added character
 *
 * Time Complexity: O(n)
 * Space Complexity: O(1)
 */
function solve(s, t) {
  // XOR all characters from both strings
  // Characters appearing in both will cancel out
  // Only the extra character remains
  let result = 0;

  // XOR all characters in s
  for (const char of s) {
    result ^= char.charCodeAt(0);
  }

  // XOR all characters in t
  for (const char of t) {
    result ^= char.charCodeAt(0);
  }

  // Convert back to character
  return String.fromCharCode(result);
}

/**
 * Test cases for Problem 389: Find
 */
function testSolution() {
  console.log("Testing 389. Find");

  // Test case 1: Basic case
  const result1 = solve("abcd", "abcde");
  const expected1 = "e";
  console.assert(
    result1 === expected1,
    `Test 1 failed: expected ${expected1}, got ${result1}`,
  );

  // Test case 2: Empty original string
  const result2 = solve("", "y");
  const expected2 = "y";
  console.assert(
    result2 === expected2,
    `Test 2 failed: expected ${expected2}, got ${result2}`,
  );

  // Test case 3: Different position
  const result3 = solve("a", "aa");
  const expected3 = "a";
  console.assert(
    result3 === expected3,
    `Test 3 failed: expected ${expected3}, got ${result3}`,
  );

  // Test case 4: Multiple same characters
  const result4 = solve("aabbcc", "aabbccd");
  const expected4 = "d";
  console.assert(
    result4 === expected4,
    `Test 4 failed: expected ${expected4}, got ${result4}`,
  );

  // Test case 5: Long string
  const result5 = solve("abcdefghijklm", "abcdefghijklmn");
  const expected5 = "n";
  console.assert(
    result5 === expected5,
    `Test 5 failed: expected ${expected5}, got ${result5}`,
  );

  console.log("All test cases passed for 389. Find!");
}

/**
 * Example usage and demonstration
 */
function demonstrateSolution() {
  console.log("\n=== Problem 389. Find ===");
  console.log("Category: Bit Manipulation");
  console.log("Difficulty: Medium");
  console.log("");

  // Example demonstration would go here
  testSolution();
}

// Run tests if this file is executed directly
if (require.main === module) {
  demonstrateSolution();
}

// Export for use in other modules
module.exports = {
  solve,
  testSolution,
  demonstrateSolution,
};

/**
 * Additional Notes:
 * - This solution focuses on bit manipulation concepts
 * - Consider the trade-offs between time and space complexity
 * - Edge cases are crucial for robust solutions
 * - The approach can be adapted for similar problems in this category
 */
